### ISSUE TITLE
More trackpad gestures

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tanin47/noo#1]
**Providing more trackpad gestures would make the app greater and more useful.**
Gestures like Jitouch (https://www.jitouch.com) would be good.

- One-Fix Left-Tap
- One-Fix Right-Tap
- One-Fix One-Slide
- One-Fix Two-Slide-Up
- One-Fix Two-Slide-Down
- One-Fix-Press Two-Slide-Up
- One-Fix-Press Two-Slide-Down
- Two-Fix Index-Double-Tap
- Two-Fix Middle-Double-Tap
- Two-Fix Ring-Double-Tap
- Two-Fix One-Slide-Up
- Two-Fix One-Slide-Down
- Two-Fix One-Slide-Left
- Two-Fix One-Slide-Right
- Three-Finger Tap
- Three-Finger Click
- Three-Finger Pinch-In
- Three-Finger Pinch-Out
- Three-Swipe-Up
- Three-Swipe-Down
- Three-Swipe-Left
- Three-Swipe-Right
- Four-Finger Click
- Four-Swipe-Up
- Four-Swipe-Down
- Four-Swipe-Left
- Four-Swipe-Right
- Pinky-To-Index
- Index-To-Pinky
- Left-Slide Scroll
- Right-Slide Scroll

**Comment by HIBIKI-CUBE** [comment]
Note: Jitouch is almost legacy software and its latest version 2.74-beta was released for macOS Mojave and it was 2017. Of course, it doesn't support Apple Silicon.

**Comment by tanin47** [comment]
Thank you for opening an issue @HIBIKI-CUBE! These gestures would be great enhancement to Noo.

Some of these gestures are difficult to detect (e.g. Four-Swipe-Up). I wonder if you happen to know whether there's a way to detect all these gestures (e.g. libraries or frameworks from Apple).

**Comment by HIBIKI-CUBE** [comment]
Unfortunately, I don't have any knowledge of interacting with the Magic trackpad.
However, I guess such special gestures are not be used much. Three-finger gestures should be more common and handy.

**Comment by tanin47** [comment]
I don't think we'll implement this feature because it requires a lot more work.

**Comment by AntonioRedondo** [comment]
It would be awesome if these gestures were supported by Noo. But if macOS doesn't offer any native API for this the detection will be difficult to implement.
