### ISSUE TITLE
Noo can't assign to another Mouse Button

### ISSUE THREAD

**Issue by swhobbit** [tanin47/noo#10]
The Logitech MarbleMouse has four buttons: 1, 2, 4, 5,  I need to assign button 4 (left inner) to Mouse Button 3, but I don't see an option for any target buttons in the menu.

**Comment by tanin47** [comment]
I apologize for the delay. I've released a new version that will make assigning a mouse button easier. You can click the mouse button, and the corresponding mouse number on the settings window will blink.

You can download a new version (released today) here: https://apps.apple.com/us/app/noo-mouse/id1514904040?mt=12
