### ISSUE TITLE
Not working on Ventura 13.2.1

### ISSUE THREAD

**Issue by ikarianDesign** [tanin47/noo#11]
Able to install through Mac apps store. Able to provide permissions, but when I open nothing happens.
Expecting to see button assignment UI window.
Thanks.

**Comment by ikarianDesign** [comment]
Works fine. My bad, didn't know I had to click the menu icon to launch it.

**Comment by tanin47** [comment]
Thank you for choosing Noo!

I'll update the README to be clearer. One tip is that you should add Noo in the startup app list: https://support.apple.com/guide/mac-help/open-items-automatically-when-you-log-in-mh15189/mac
