### ISSUE TITLE
After enter Full Screen mode, it has no button to come back to windows mode also missing "Enter" mapping to a button

### ISSUE THREAD

**Issue by fabriciofri** [tanin47/noo#17]
After enter Full Screen mode, it has no button to come back to windows mode also missing "Enter" mapping to a button, 

I am on Mac M1 2021

BR
Fabricio

**Comment by tanin47** [comment]
First of all, thank you so much for supporting and using Noo.

> "Enter"

This is called "Return". I'll improve it by changing it to `Return (Enter)`


Regarding the full screen mode like below:

<img width="1440" alt="image" src="https://github.com/tanin47/noo/assets/494417/b6289120-4b2b-4b19-b43d-b8d342344604">

If you want to go back, you can press "Esc" or you would have to move the mouse to the top, then the top bar will appear like this:

<img width="1440" alt="image" src="https://github.com/tanin47/noo/assets/494417/d72e2894-a912-4b34-8473-1c52995be85e">

Then, you can click on the green circle to exit the full screen mode.

I hope this is helpful.
