### ISSUE TITLE
Universal build

### ISSUE THREAD

**Issue by smitterson** [tanin47/noo#3]
Hi, just found this app and started using it on my M1 Mac. Wondering if its possible for you to publish a universal build to the App Store?

**Comment by tanin47** [comment]
Could you clarify what "a universal build" mean? We definitely publish to App Store here: https://apps.apple.com/us/app/noo-mouse/id1514904040

**Comment by smitterson** [comment]
Hi,

I have installed the app from the App Store. What I meant is the app is built for Intel Macs only, meaning it has to run via Rosetta 2 on Apple Silicon Macs. I was wondering you were able to post a new build that was a universal binary that also runs natively on Apple Silicon Macs. 

<img width="279" alt="image" src="https://user-images.githubusercontent.com/271235/110948199-0d8ca000-830f-11eb-8802-37490fe063ad.png">

**Comment by VarenSwaab** [comment]
I would also like to get an M1 build for Noo. I find this little utility to be ideal for my setup and it works perfectly. Please update for Apple silicon.

**Comment by tanin47** [comment]
Thank you for all the input. I'll figure out how to do this. Please let me know if you know a good instruction.

**Comment by tanin47** [comment]
Hi @VarenSwaab and @smitterson, I apologize for the delay. I've made the universal build (turns out to be very easy). Please try and let me know: https://github.com/tanin47/noo/releases/tag/2.0

![image](https://user-images.githubusercontent.com/494417/131228346-a057df05-c447-4045-af30-cca8e3c09b08.png)

**Comment by VarenSwaab** [comment]
Thanks very much for updating the app. It's very much appreciated!
