### ISSUE TITLE
Noo not working in M1 Macs

### ISSUE THREAD

**Issue by VarenSwaab** [tanin47/noo#5]
I just downloaded Noo from the Mac App Store and when I open it there is a message that requests to install Rosetta. I thought this update was recompiled to run on M1 Macs? Perhaps the file wasn't updated. Why isn't the App Store file working as expected?

**Comment by tanin47** [comment]
I have no idea. It seems I didn't build the universal artifact correctly. I'll need to take some time to investigate this.

**Comment by VarenSwaab** [comment]
<img width="576" alt="Screen Shot 2022-05-27 at 11 38 21" src="https://user-images.githubusercontent.com/5083862/170771101-f19d9dd7-2537-4685-b140-e37f920da225.png">

I've attached a screenshot of the problem with the downloaded version from the App Store. It seems the M1 version of Noo isn't working in the current version of the app. Can you fix this? Thanks.

**Comment by tanin47** [comment]
Apology for the delay. I've now been able to build the universal build for Noo using Xcode Cloud.

You can install the new version from the App Store: https://apps.apple.com/us/app/noo-mouse/id1514904040?mt=12
